"""Evidence-based HTTP device contracts and a local, offline device stand-in.

No inference here claims to discover unseen endpoints or physical behaviour.
Captured bodies are retained in full; samples are never generated by an LLM.
"""
import base64
import copy
import json
import threading
from collections import defaultdict
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import parse_qsl, urlsplit

from .session import Session, _parse
from .sources import har

FORMAT = "mimic-device/v1"
REDACTED = "<redacted>"
METHODS = {"GET", "POST", "PUT", "PATCH", "DELETE", "HEAD", "OPTIONS"}
SECRET_NAMES = {"authorization", "cookie", "setcookie", "password", "passwd", "secret",
                "token", "accesstoken", "refreshtoken", "apikey", "sessiontoken",
                "clientsecret", "bearertoken"}


def _secret(key):
    name = "".join(c for c in key.lower() if c.isalnum())
    return name in SECRET_NAMES or name.endswith(("token", "password", "secret", "apikey"))


def redact(value):
    """Best-effort removal of credentials identified by JSON/query field name."""
    if isinstance(value, dict):
        return {k: REDACTED if _secret(k) else redact(v) for k, v in value.items()}
    if isinstance(value, list):
        return [redact(v) for v in value]
    return value


def _body(raw, content_type=""):
    if isinstance(raw, str):
        raw = raw.encode("utf-8")
    if not raw:
        return {"kind": "empty", "value": None}
    try:
        text = raw.decode("utf-8")
    except UnicodeDecodeError:
        return {"kind": "base64", "value": base64.b64encode(raw).decode("ascii")}
    try:
        return {"kind": "json", "value": redact(json.loads(text))}
    except ValueError:
        if "application/x-www-form-urlencoded" in content_type:
            pairs = [[k, REDACTED if _secret(k) else v] for k, v in parse_qsl(text, keep_blank_values=True)]
            return {"kind": "form", "value": pairs}
        return {"kind": "text", "value": text}


def _content_type(headers):
    return next((v for k, v in headers if k.lower() == "content-type"), "")


def observation(method, url, request_body, response_body, status, request_headers=(), response_headers=()):
    parsed = urlsplit(url)
    if parsed.scheme not in ("http", "https") or not parsed.hostname:
        raise ValueError("device observations require an HTTP(S) URL")
    method = method.upper()
    if method not in METHODS or not 200 <= status <= 599:
        raise ValueError("only ordinary HTTP exchanges are supported (no WebSocket upgrades)")
    query = sorted([[k, REDACTED if _secret(k) else v] for k, v in parse_qsl(parsed.query, keep_blank_values=True)])
    req_type = _content_type(request_headers)
    resp_type = _content_type(response_headers)
    return {
        "method": method, "path": parsed.path or "/", "query": query,
        "request": _body(request_body, req_type), "request_content_type": req_type,
        "response": {"status": status, "content_type": resp_type,
                     "body": _body(response_body, resp_type)},
    }


def infer_schema(values):
    """JSON Schema from *all* samples; required means present in every sample.

    No enums, bounds, formats, or unseen behaviours are guessed. Empty arrays
    leave items unconstrained. Null, heterogeneous lists, and optional fields
    are preserved instead of forcing the most recent example's shape.
    """
    if not values:
        return {}
    grouped = defaultdict(list)
    for value in values:
        kind = ("null" if value is None else "boolean" if isinstance(value, bool)
                else "integer" if isinstance(value, int) else "number" if isinstance(value, float)
                else "string" if isinstance(value, str) else "object" if isinstance(value, dict)
                else "array" if isinstance(value, list) else None)
        if kind is None:
            raise ValueError("schema inference accepts JSON values only")
        grouped[kind].append(value)
    if "integer" in grouped and "number" in grouped:
        grouped["number"].extend(grouped.pop("integer"))
    schemas = []
    for kind, samples in sorted(grouped.items()):
        schema = {"type": kind}
        if kind == "object":
            keys = sorted({k for sample in samples for k in sample})
            schema["properties"] = {k: infer_schema([v[k] for v in samples if k in v]) for k in keys}
            schema["required"] = [k for k in keys if all(k in v for v in samples)]
            schema["additionalProperties"] = True
        elif kind == "array":
            schema["items"] = infer_schema([v for sample in samples for v in sample])
        schemas.append(schema)
    return schemas[0] if len(schemas) == 1 else {"anyOf": schemas}


def make_profile(host, observations):
    observations = list(observations)
    if not observations:
        raise ValueError("no completed exchanges for this host")
    return {"format": FORMAT, "host": host,
            "evidence": {"source": "observed HTTP exchanges", "sample_count": len(observations),
                         "unseen_behavior": "unknown", "redaction": "credential field names; review other data before sharing"},
            "observations": observations, "initial_state": {}, "rules": []}


def profile_from_har(path, host):
    with open(path, encoding="utf-8") as f:
        entries = json.load(f).get("log", {}).get("entries", [])
    observations = []
    for entry in entries:
        req, resp = entry.get("request", {}), entry.get("response", {})
        if urlsplit(req.get("url", "")).hostname != host:
            continue
        if not resp.get("status"):
            continue  # failed/incomplete exchange has no observed response
        content = resp.get("content", {})
        bodyless = req.get("method") == "HEAD" or resp.get("status") in (204, 304)
        known_empty = content.get("size") == 0 or resp.get("bodySize") == 0
        if "text" not in content and not (bodyless or known_empty):
            raise ValueError("HAR response body omitted; export HAR with content before learning")
        if content.get("encoding") == "base64":
            try:
                raw = base64.b64decode(content.get("text", ""), validate=True)
            except ValueError as exc:
                raise ValueError("invalid base64 HAR response") from exc
        else:
            raw = content.get("text", "").encode("utf-8")
        req_headers = [(h["name"], h["value"]) for h in req.get("headers", [])]
        resp_headers = [(h["name"], h["value"]) for h in resp.get("headers", [])]
        if not _content_type(resp_headers) and content.get("mimeType"):
            resp_headers.append(("Content-Type", content["mimeType"]))
        post_data = req.get("postData", {})
        if not _content_type(req_headers) and post_data.get("mimeType"):
            req_headers.append(("Content-Type", post_data["mimeType"]))
        if (post_data or req.get("bodySize", 0) > 0) and not any(k in post_data for k in ("text", "params")):
            raise ValueError("HAR request body omitted; export HAR with request content")
        observations.append(observation(req["method"], req["url"], har._body_bytes(post_data),
                                        raw, resp.get("status", 0), req_headers, resp_headers))
    return make_profile(host, observations)


def profile_from_mitm(client, flows, host):
    observations = []
    for flow in flows:
        req, resp = flow.get("request") or {}, flow.get("response") or {}
        if req.get("host") != host or not resp:
            continue
        netloc = host if ":" not in host else f"[{host}]"
        if req.get("port"):
            netloc += f":{req['port']}"
        url = f"{req.get('scheme', 'http')}://{netloc}{req['path']}"
        observations.append(observation(req["method"], url, client.body(flow["id"], "request"),
                                        client.body(flow["id"], "response"), resp["status_code"],
                                        req.get("headers", []), resp.get("headers", [])))
    return make_profile(host, observations)


def save_profile(profile, path):
    with open(path, "w", encoding="utf-8") as f:
        json.dump(profile, f, indent=2, ensure_ascii=False)
        f.write("\n")


def load_profile(path):
    with open(path, encoding="utf-8") as f:
        profile = json.load(f)
    if profile.get("format") != FORMAT:
        raise ValueError(f"expected profile format {FORMAT}")
    return profile


def openapi(profile):
    """OpenAPI 3.1 contract, explicitly marked as observational, for any harness."""
    groups = defaultdict(list)
    for obs in profile["observations"]:
        groups[(obs["path"], obs["method"])].append(obs)
    paths = {}
    for (path, method), samples in sorted(groups.items()):
        query_names = sorted({k for sample in samples for k, _ in sample["query"]})
        op = {"summary": f"Observed {method} {path}", "x-mimic-sample-count": len(samples),
              "x-mimic-unseen-behavior": "unknown", "responses": {}, "parameters": []}
        for name in query_names:
            repeated = any(sum(k == name for k, _ in s["query"]) > 1 for s in samples)
            op["parameters"].append({"name": name, "in": "query", "required": all(any(k == name for k, _ in s["query"]) for s in samples),
                                     "schema": {"type": "array", "items": {"type": "string"}} if repeated else {"type": "string"}})
        body_groups = defaultdict(list)
        response_groups = defaultdict(list)
        for sample in samples:
            if sample["request"]["kind"] != "empty":
                mime = sample["request_content_type"] or ("application/json" if sample["request"]["kind"] == "json" else "application/octet-stream")
                body_groups[mime].append(sample["request"])
            response_groups[str(sample["response"]["status"])].append(sample["response"])
        if body_groups:
            op["requestBody"] = {"required": all(s["request"]["kind"] != "empty" for s in samples),
                                 "content": {mime: {"schema": _body_schema(bodies)} for mime, bodies in sorted(body_groups.items())}}
        for status, responses in sorted(response_groups.items()):
            content = defaultdict(list)
            for resp in responses:
                if resp["body"]["kind"] != "empty":
                    mime = resp["content_type"] or ("application/json" if resp["body"]["kind"] == "json" else "application/octet-stream")
                    content[mime].append(resp["body"])
            op["responses"][status] = {"description": f"Observed HTTP {status}", "x-mimic-sample-count": len(responses)}
            if content:
                op["responses"][status]["content"] = {mime: {"schema": _body_schema(bodies)} for mime, bodies in sorted(content.items())}
        paths.setdefault(path, {})[method.lower()] = op
    return {"openapi": "3.1.0", "info": {"title": f"Observed device API: {profile['host']}", "version": "0.1.0",
            "description": "Inferred from captures, not a complete device specification. Required fields are observational. Behaviour outside captured examples is unknown."},
            "servers": [{"url": "http://127.0.0.1:8090", "description": "Local emulator (override if using another port)"}],
            "paths": paths}


def _body_schema(bodies):
    if all(b["kind"] == "json" for b in bodies):
        return infer_schema([b["value"] for b in bodies])
    return {"type": "string", "description": "Raw captured HTTP body; not inferred as JSON"}


class RecordingSession(Session):
    """Explicit calls to one device origin; records replies including HTTP errors.

    Redirects are disabled to avoid unnoticed calls to other hosts. No probing,
    automatic retries, or credential refresh. Inherits the existing verb helpers.
    """
    def __init__(self, base_url, headers=None, timeout=10):
        origin = urlsplit(base_url)
        if origin.scheme not in ("http", "https") or not origin.hostname or origin.username or origin.password:
            raise ValueError("base_url must be an HTTP(S) origin without credentials")
        if origin.path not in ("", "/") or origin.query or origin.fragment:
            raise ValueError("base_url must be an origin; pass paths to request()")
        super().__init__(base_url, headers=headers)
        self.timeout = timeout
        self.observations = []

    def request(self, method, path, json=None, params=None, refresh=None, **kw):
        if method.upper() not in METHODS:
            raise ValueError("unsupported device HTTP method")
        if not path.startswith("/") or path.startswith("//"):
            raise ValueError("recorded paths must begin with / and stay on the device origin")
        if kw.get("allow_redirects"):
            raise ValueError("redirects are disabled for device capture")
        kw["allow_redirects"] = False
        kw.setdefault("timeout", self.timeout)
        headers = dict(self.headers)
        headers.update(kw.pop("headers", {}) or {})
        response = self._http.request(method, f"{self.base_url}{path}", headers=headers,
                                      json=json, params=params, **kw)
        self.observations.append(observation(method, response.request.url, response.request.body or b"",
                                            response.content, response.status_code,
                                            response.request.headers.items(), response.headers.items()))
        response.raise_for_status()
        return _parse(response)

    def profile(self):
        return make_profile(urlsplit(self.base_url).hostname, self.observations)

    def save(self, path):
        save_profile(self.profile(), path)


def _signature(method, path, query, body):
    return json.dumps([method, path, sorted(query), body], sort_keys=True, separators=(",", ":"))


def _subset(expected, actual):
    if isinstance(expected, dict):
        return isinstance(actual, dict) and all(k in actual and _subset(v, actual[k]) for k, v in expected.items())
    return expected == actual and type(expected) is type(actual)


def _pointer(value, pointer):
    if pointer == "":
        return value
    if not isinstance(pointer, str) or not pointer.startswith("/"):
        raise ValueError("template pointers must be JSON Pointers starting with /")
    for key in pointer[1:].split("/"):
        key = key.replace("~1", "/").replace("~0", "~")
        if isinstance(value, list):
            if not key.isdigit() or (len(key) > 1 and key.startswith("0")):
                raise ValueError("invalid JSON Pointer array index")
            value = value[int(key)]
        else:
            value = value[key]
    return copy.deepcopy(value)


def _resolve(template, context):
    if isinstance(template, dict):
        if set(template) == {"$ref"}:
            return _pointer(context, template["$ref"])
        return {k: _resolve(v, context) for k, v in template.items()}
    if isinstance(template, list):
        return [_resolve(v, context) for v in template]
    return copy.deepcopy(template)


def _wire(body):
    kind, value = body["kind"], body["value"]
    if kind == "empty":
        return b""
    if kind == "base64":
        return base64.b64decode(value, validate=True)
    if kind == "json":
        return json.dumps(value, ensure_ascii=False).encode("utf-8")
    if kind == "form":
        from urllib.parse import urlencode
        return urlencode([tuple(pair) for pair in value]).encode("utf-8")
    if kind == "text":
        return value.encode("utf-8")
    raise ValueError(f"unknown body kind: {kind}")


class DeviceEmulator:
    """Strict replay plus explicit state rules; never forwards to a real device.

    Each exact request has its own response sequence, holding its final reply
    once exhausted. Rules take precedence and are labelled manual behaviour.
    All matching, counter updates, and state transitions are atomic.
    """
    def __init__(self, profile):
        if profile.get("format") != FORMAT:
            raise ValueError(f"expected profile format {FORMAT}")
        self.profile = copy.deepcopy(profile)
        self.state = copy.deepcopy(profile.get("initial_state", {}))
        if not isinstance(self.state, dict):
            raise ValueError("initial_state must be an object")
        self._lock = threading.RLock()
        self._counts = defaultdict(int)
        self._responses = defaultdict(list)
        self._routes = set()
        for obs in self.profile["observations"]:
            if obs.get("method") not in METHODS or not obs.get("path", "").startswith("/"):
                raise ValueError("observations need an HTTP method and absolute path")
            response = obs["response"]
            if not 200 <= response.get("status", 0) <= 599:
                raise ValueError("observation response status must be 200..599")
            content_type = response.get("content_type", "")
            if not isinstance(content_type, str) or any(c in content_type for c in "\r\n"):
                raise ValueError("invalid captured Content-Type")
            _wire(obs["request"])
            _wire(obs["response"]["body"])
            self._responses[_signature(obs["method"], obs["path"], obs["query"], obs["request"])].append(obs["response"])
            self._routes.add((obs["method"], obs["path"]))
        for rule in profile.get("rules", []):
            if rule.get("method") not in METHODS or not rule.get("path", "").startswith("/"):
                raise ValueError("rules need an HTTP method and absolute path")
            if not isinstance(rule.get("set_state", {}), dict) or not isinstance(rule.get("when_state", {}), dict):
                raise ValueError("rule state conditions and updates must be objects")
            if not 200 <= rule.get("status", 200) <= 599:
                raise ValueError("rule status must be 200..599")

    def reset(self):
        with self._lock:
            self.state = copy.deepcopy(self.profile.get("initial_state", {}))
            self._counts.clear()

    def dispatch(self, method, target, raw=b"", content_type=""):
        parsed = urlsplit(target)
        query = sorted([[k, REDACTED if _secret(k) else v] for k, v in parse_qsl(parsed.query, keep_blank_values=True)])
        body = _body(raw, content_type)
        path = parsed.path or "/"
        with self._lock:
            for rule in self.profile.get("rules", []):
                if (rule["method"], rule["path"]) != (method, path):
                    continue
                if not _subset(rule.get("when_state", {}), self.state):
                    continue
                if "request_json" in rule and (body["kind"] != "json" or not _subset(rule["request_json"], body["value"])):
                    continue
                if "query" in rule and sorted(rule["query"]) != query:
                    continue
                context = {"request": body["value"], "state": copy.deepcopy(self.state)}
                try:
                    updates = _resolve(rule.get("set_state", {}), context)
                    next_state = {**self.state, **updates}
                    context["state"] = next_state
                    result = {"status": rule.get("status", 200), "content_type": "application/json",
                              "body": {"kind": "json", "value": _resolve(rule.get("response_json"), context)}}
                    _wire(result["body"])
                except (KeyError, IndexError, TypeError, ValueError) as exc:
                    return self._error(422, f"manual rule template could not be resolved: {type(exc).__name__}"), "manual-rule-error"
                self.state = next_state
                return result, "manual-rule"
            key = _signature(method, path, query, body)
            if key not in self._responses:
                status = 409 if (method, path) in self._routes else 404
                return self._error(status, "no captured exchange or explicit rule matches this request; unseen behaviour is unknown"), "unmatched"
            responses = self._responses[key]
            index = min(self._counts[key], len(responses) - 1)
            self._counts[key] += 1
            return copy.deepcopy(responses[index]), "captured-replay"

    @staticmethod
    def _error(status, message):
        return {"status": status, "content_type": "application/json", "body": {"kind": "json", "value": {"error": message}}}

    def server(self, bind="127.0.0.1", port=8090):
        emulator = self

        class Handler(BaseHTTPRequestHandler):
            def handle_request(self):
                if self.headers.get("Transfer-Encoding"):
                    self.send_error(400, "chunked request bodies are unsupported")
                    return
                try:
                    size = int(self.headers.get("Content-Length", "0"))
                    if size < 0 or size > 16 * 1024 * 1024:
                        self.send_error(413, "request body limit is 16 MiB")
                        return
                except ValueError:
                    self.send_error(400, "invalid Content-Length")
                    return
                raw = self.rfile.read(size)
                resp, source = emulator.dispatch(self.command, self.path, raw, self.headers.get("Content-Type", ""))
                payload = _wire(resp["body"])
                if resp["status"] in (204, 304):
                    payload = b""
                self.send_response(resp["status"])
                self.send_header("Content-Type", resp["content_type"] or "application/octet-stream")
                self.send_header("X-Mimic-Source", source)
                self.send_header("Content-Length", str(len(payload)))
                self.end_headers()
                if self.command != "HEAD":
                    self.wfile.write(payload)

            do_GET = do_POST = do_PUT = do_PATCH = do_DELETE = do_HEAD = do_OPTIONS = handle_request

            def log_message(self, format, *args):
                pass  # query/body data must not enter access logs by default

        class Server(ThreadingHTTPServer):
            daemon_threads = True

            def get_request(self):
                connection, address = super().get_request()
                connection.settimeout(10)
                return connection, address

        return Server((bind, port), Handler)
